### ISSUE TITLE
ensure control keys with additional keys (ie,. AC-1a or AC-3 (1)(a)) dont have narrative for primary key

### ISSUE THREAD

**Issue by carlosmmatos** [carlosmmatos/automate-compliance#12]
Primary Control Keys such as AC-1 that have additional subcontrols/enhancements should ensure that it doesn't have a narrative for the primary key.

Example output from Parser.data:
```
{CP-6  [{ Text only} {a Text for enhancement} {b Text for enhancement}] [] []  []  []}
```
should be:
```
{CP-6  [{a Text for enhancement} {b Text for enhancement}] [] []  []  []}
```

This is the end state OpenControl:
```yaml
- control_key: CP-6
  standard_key: NIST-800-53
  covered_by: []
  implementation_status: not applicable
  narrative:
    - key: a
      text: |-
        Text for enhancement...
    - key: b
      text: |-
        Text for enhancement...
...
```
